### PR TITLE
Handle initial network connectivity

### LINKED ISSUE #421: Blank page after internet activated
if internet isn't activated/doesn't work when the app starts, the app stays blank after internet is back

---

Caprine 2.10.0
Electron 1.8.4
linux x64 4.14.30-1-MANJARO

### PR DESCRIPTION
**Pull request by whitecrownclown**
@sindresorhus ,

Hello!

This PR should fix the initial app launch issue with network connectivity and also allow for `Caprine` to be launched on system start/login without the need of a manual refresh. (Fixes #421)

Any feedback is welcome. Thanks!

### CODE REVIEW

**Comment by CvX** [comment]
I don’t think this is a correct way to approach connectivity problems.

1. Reloading the page is one of the triggers of the bug described in #712.
2. User could be interacting with the app when the reload happens which isn’t great user experience.
3. If someone’s connection keeps dropping the app would reload constantly. Not ideal either.

We have to find a different way to force Messenger to re-establish its connections.

**Comment by whitecrownclown** [comment]
@CvX I know it's not a great way to do it, but this PR only handles initial connectivity, before the user has a change to interact with the app (for example, launching the app at login, when most of the time there's no internet connection and the app remains unresponsive/blank page). I'm not sure about item number 1, but definitely 2 and 3 would not apply here.

**Comment by CvX** [comment]
Ah, my bad! 😶 In this case, you’re right, disregard 2 and 3.
And to handle 1 it might be better to do what we do when switching between standard messenger and work chat?

```js
app.relaunch();
app.quit();
```

**Comment by whitecrownclown** [comment]
@CvX Yes, i could make that change, the reason why i didn't go for that at first is that to the user it will look more like a bug and it also takes a bit longer to load. Is there no way we could reload the mainWindow and find a fix for #712 ?

**Comment by CvX** [comment]
That would be ideal, but I'm afraid it might take quite a while to fix #712, since it's possibly a bug in Chromium.

I'd suggest doing a full app relaunch for now and adding a TODO comment to remind us to change it to a simple reload as soon as #712 is fixed.

**Comment by whitecrownclown** [comment]
@CvX Alright, i've done exactly that. Thanks!

File: source/index.ts [hunk 1]
```diff
@@ -276,6 +277,13 @@ function createMainWindow(): BrowserWindow {
 	return win;
 }
 
+const networkConnectivity = async (): Promise<boolean> => {
```
Comment (CvX) [inline source/index.ts]:
```suggestion
const networkConnectivity = async (): Promise<true> => {
```

File: source/index.ts [hunk 2]
```diff
@@ -276,6 +277,13 @@ function createMainWindow(): BrowserWindow {
...
+	/* eslint-disable no-await-in-loop */
```
Comment (CvX) [inline source/index.ts]:
```suggestion
	/* eslint-disable-next-line no-await-in-loop */
```

File: source/index.ts [hunk 3]
```diff
@@ -276,6 +277,13 @@ function createMainWindow(): BrowserWindow {
...
+	while (!(await isOnline()));
+	/* eslint-enable no-await-in-loop */
```
Comment (CvX) [inline source/index.ts]:
```suggestion
```

**Comment by whitecrownclown** [comment]
@CvX I've updated the PR and also used `p-wait-for` instead of the `while` statement.

File: source/index.ts [hunk 4]
```diff
@@ -285,6 +287,12 @@ function createMainWindow(): BrowserWindow {
 	mainWindow = createMainWindow();
 	tray.create(mainWindow);
 
+	// TODO: Reload mainWindow instead as soon as #712 is fixed
+	if (!(await isOnline()) && (await pWaitFor(isOnline), {interval: 1000})) {
```
Comment (CvX) [inline source/index.ts]: 1. There's a bug – the options object with `interval` isn't actually passed into the `pWaitFor` 😉
2. It might be more readable to move the second await inside the block:

```suggestion
	if (!await isOnline()) {
		await pWaitFor(isOnline, {interval: 1000});
```

Comment (whitecrownclown) [reply source/index.ts]: 1. I somehow missed that from too many parenthesis. 2. That's the reason i missed nr. 1

Comment (CvX) [reply source/index.ts]: You can also get rid of the extra parens around `await isOnline()` (see the previous suggestion). 🙂

Comment (whitecrownclown) [reply source/index.ts]: @CvX The linter won't really let me do that inside an if condition

Comment (CvX) [reply source/index.ts]: Ah, my bad, some linter errors don't show up in my text editor due to a bug… 😓

**Comment by sindresorhus** [comment]
This results in a weird experience if you're actually offline. Then the app is just on the Dock without anything happening or showing. I think we need a timeout after 20 (?) seconds where it shows an error message to the user that they're offline, and with a "try again" button.

File: source/index.ts [hunk 5]
```diff
@@ -289,7 +289,11 @@ function createMainWindow(): BrowserWindow {
 
 	// TODO: Reload mainWindow instead as soon as #712 is fixed
 	if (!(await isOnline())) {
+		const connectivityTimeout = setTimeout(() => {
+			showRetryDialog(`It appears that you're offline`);
```
Comment (sindresorhus) [inline source/index.ts]: > You appear to be offline. Caprine requires a working internet connection.

?

**Comment by CvX** [comment]
I've tried the this PR on Windows, and a couple of times the relaunched app's window was blank. I didn't find out the root cause, but instead I decided to try a simpler solution: wait for the connection **before** creating the window. Let me know what you think @whitecrownclown, @sindresorhus.

**Comment by whitecrownclown** [comment]
@CvX I think it's both simpler and better. No need to relaunch app/ reload window. I did notice that after this change triggering window 'activate' will throw and error so i added in a small check.

File: source/util.ts [hunk 6]
```diff
@@ -33,3 +33,20 @@ export function showRestartDialog(message: string): void {
 		}
 	);
 }
+
+export function showRetryDialog(message: string): void {
```
Comment (sindresorhus) [inline source/util.ts]: This is not really a generic utility. I would move this and https://github.com/sindresorhus/caprine/pull/775/files#diff-21e9ddd93162651bd36f6e5bbfca8460R282 into a new file to contain the logic.

So in `index.js`, it would just be:

```js
(async () => {
await ensureOnline();

await app.whenReady();

...
```

**Comment by sindresorhus** [comment]
@CvX Good solution!

File: source/util.ts (hunk 6 above)
Comment (CvX) [reply source/util.ts]: btw. these awaits don't have to be sequential, so we can change that to, e.g.:

```js
await Promise.all([ensureOnline(), app.whenReady()]);
```

**Comment by CvX** [comment]
I've renamed `showRetryDialog` to `showWaitDialog` and did some minor cleanup.

**Comment by CvX** [comment]
@sindresorhus Prettier disagrees with you 😉

**Comment by sindresorhus** [comment]
Good work everyone :)

File: source/util.ts (hunk 6 above)
Comment (sindresorhus) [reply source/util.ts]: @CvX There's not really any benefit in using `Promise.all` here as `app.whenReady()` doesn't do any work. It's just a shortcut for checking for the status of the app load. So the result of using `Promise.all` is exactly the same as before. But it's fine, we can keep it.
