### PR TITLE
Bump Electron to 0.37.8 and fix deprecated methods

### LINKED ISSUE #83: Fix the shortcuts shown in the text zoom menu items
From https://github.com/sindresorhus/caprine/pull/81#discussion_r60851232.

It's an Electron bug: https://github.com/electron/electron/issues/1507

### PR DESCRIPTION
**Pull request by danhp**
Bump to 0.37.8 to fix #83 
Also use https://github.com/danhp/electron-osx-appearance as `app.isDarkMode()` and `platform-theme-changed` event got deprecated. Ref https://github.com/electron/electron/pull/5282

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think you misunderstood. It was only moved: https://github.com/electron/electron/blob/master/docs/api/system-preferences.md#systempreferencesisdarkmode-os-x

**Comment by danhp** [comment]
They were moved but the code turned out quite long so I wrote a wrapper for it.

**Comment by sindresorhus** [comment]
`systemPreferences.isDarkMode()` is still there.

File: browser.js [hunk 1]
```diff
@@ -57,10 +58,12 @@ ipc.on('archive-conversation', () => {
 
 ipc.on('dark-mode', toggleDarkMode);
 
-app.on('platform-theme-changed', () => {
-	storage.set('darkMode', app.isDarkMode());
-	setDarkMode();
-});
+if (process.platform === 'darwin') {
+	osxAppearance.onDarkModeChanged(() => {
```
Comment (sindresorhus) [inline browser.js]: `prefs.subscribeNotification('AppleInterfaceThemeChangedNotification', () => {`

**Comment by danhp** [comment]
Woops, I'll put that back.

**Comment by sindresorhus** [comment]
Actually, it's nicer with your module. Let's use it.

**Comment by sindresorhus** [comment]
But update it to use the native `.isDarkMode()` method.

**Comment by danhp** [comment]
Sounds good, I'll update the module.

**Comment by sindresorhus** [comment]
Why limit the module to just appearance. I bet there are lots of useful defaults you can get with `systemPreferences.getUserDefault` other than appearance stuff.

**Comment by sindresorhus** [comment]
And don't forget to add the module to https://github.com/sindresorhus/awesome-electron in two weeks ;)

**Comment by danhp** [comment]
I wanted to keep the module as focused as possible. But yeah, you can do a lot with `getUserDefaults`, the only problem is that you need to know the name and the exact type associated with it.

**Comment by sindresorhus** [comment]
> the only problem is that you need to know the name and the exact type associated with it.

That's why a wrapper module would be so useful. Don't really care if it's part of the current one or a new one. Just a thought if you're looking for project ideas ;)

File: menu.js [hunk 2]
```diff
@@ -26,7 +26,7 @@ const viewSubmenu = [
 	},
 	{
 		label: 'Increase Text Size',
-		accelerator: 'CmdOrCtrl+=',
+		accelerator: 'CmdOrCtrl+Plus',
```
Comment (sindresorhus) [inline menu.js]: This requires using `Cmd Shift +` now. ?

Comment (danhp) [inline menu.js]: Weird... I get 
image

Comment (sindresorhus) [inline menu.js]: I get that too, but it only works when I use the above shortcut. Not what's shown. Try.

Comment (danhp) [inline menu.js]: My plus is only accessible through shift so that's the only command I can input...

Comment (sindresorhus) [inline menu.js]: Ah, you're right. Just weird that minus is placed on the keyboard so that it doesn't need Shift, while Plus does. Not the best design...

> Unless you mean we have both Cmd+= and Cmd+Plus be mapped to the same action?

That would be favorable. See and vote for: https://github.com/electron/electron/issues/5256

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by danhp** [comment]
http://giphy.com/gifs/shaun-the-sheep-movie-not-my-gif-2016-oscar-nominations-tIeCLkB8geYtW

**Comment by danhp** [comment]
No Problem
