### PR TITLE
Fix `Increase Text Size` shortcut

### LINKED ISSUE #926: Keyboard shortcut (Command +) not working
The "command +" shortcut to increase text size does not work in OS X Mojave!  

---

Caprine 2.31.2
Electron 5.0.2
darwin 18.6.0
Locale: en-GB

### PR DESCRIPTION
**Pull request by whitecrownclown**
Fixes #926 

@sindresorhus 	

Used [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) to enable `CommandOrControl+=` for `zoom-in`

### CODE REVIEW

File: source/index.ts [hunk 1]
```diff
@@ -289,6 +290,11 @@ function createMainWindow(): BrowserWindow {
 
 	await updateAppMenu();
 	mainWindow = createMainWindow();
+
+	electronLocalshortcut.register(mainWindow, 'CommandOrControl+=', () => {
```
Comment (sindresorhus) [inline source/index.ts]: Can you add a comment that this is a workaround and link to the Electron issue.

File: source/index.ts [hunk 2]
```diff
@@ -297,6 +298,12 @@ function createMainWindow(): BrowserWindow {
 	await updateAppMenu();
 	mainWindow = createMainWindow();
 
+	// Workaround for https://github.com/electron/electron/issues/5256
+	electronLocalshortcut.register(mainWindow, 'CommandOrControl+=', () => {
+		sendAction('zoom-in');
+	});
+
+	tray.create(mainWindow);
```
Comment (sindresorhus) [inline source/index.ts]: ?
