### PR TITLE
[Fix] Emoji picker crashes app

### LINKED ISSUE #1185: App goes blank after clicking emoji button
(I have the app set to dark mode)
When I try to click on the emoji button in the chat window, your messenger app goes black. If I want to fix it I need to quit the app and relaunch it. But the same thing happens again when I click on the emoji button, so it is really easy to reproduce.

---

Caprine 2.41.1
Electron 7.1.1
darwin 18.7.0
Locale: nb

### PR DESCRIPTION
**Pull request by whitecrownclown**
Fixes #1185 
Closes #1234

Please have a look, thanks! 
cc @CvX @sindresorhus

### CODE REVIEW

File: source/browser.ts [hunk 1]
```diff
@@ -281,12 +281,7 @@ async function setPrivateMode(): Promise<void> {
 	document.documentElement.classList.toggle('private-mode', config.get('privateMode'));
 
 	if (is.macos) {
-		if (config.get('privateMode')) {
-			ipc.send('hide-touchbar-labels');
-		} else {
-			const conversationsToRender: Conversation[] = await createConversationList();
-			ipc.send('conversations', conversationsToRender);
-		}
+		await sendConversationList();
```
Comment (CvX) [inline source/browser.ts]: If we no longer await for `setPrivateMode()` maybe it doesn't have to be async anymore?

Comment (whitecrownclown) [reply source/browser.ts]: We need it to be async since we’re doing sendConversationList

Comment (CvX) [reply source/browser.ts]: But we're don't need to await for `sendConversationList()` anymore either, since we don't do anything after it is called, right?

**Comment by whitecrownclown** [comment]
I think you’re right. I’ll update the PR.
