### PR TITLE
Fix window resizing/moving issues and add ability to disable vibrancy

### LINKED ISSUE #721: Windows 10: window not vissible when toggled
So I'm having a problem when I open Caprine, it shows in taskbar but when I click on taskbar the window is not showing.

### LINKED ISSUE #724: Windows 10: Maximize button greyed out
On windows 10 I cannot maximize window. The button is greyed out. Double clicking on top bar doesn't do anything.

### LINKED ISSUE #725: Windows 10: Window cannot be resized
On windows 10, window of caprine cannot be resized.

### PR DESCRIPTION
**Pull request by CvX**
Fixes #721 
Fixes #724 
Fixes #725 by reverting a faulty fix (my bad).

Also, improves the situation in #712 by providing a way to disable the vibrancy.

vibrancy menu

In a way, this PR acts as a stop-gap before a complete fix for vibrancy issues is done (though some people might like the vibrancy-less look so an option for that is a plus).

cc: @sindresorhus, @neegool

### CODE REVIEW

File: config.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ module.exports = new Store({
 	defaults: {
 		followSystemAppearance: false,
 		darkMode: false,
-		vibrancy: false,
+		vibrancy: 'none', // Possible values: 'none', 'sidebar', 'full'
```
Comment (sindresorhus) [inline config.js]: I think we should default to `'sidebar'` to be as native-looking as possible by default.

You also need to add a migration from the boolean type, in this file. This is how I have handled migrations before: https://github.com/atomiclabs/hyperdex/blob/575056075278db372a724cde549743e0ba000bb2/app/config.js#L44-L59

Comment (sindresorhus) [reply config.js]: > I think we should default to 'sidebar' to be as native-looking as possible by default.

Actually, let's wait to turn this on by default until the underlaying issue is fixed in Electron. Add a TODO comment about it however which links to the Electron issue, so we don't forget to change the default in the future.

**Comment by CvX** [comment]
As requested, I've added the TODO comment regarding the default vibrancy setting and implemented the setting migration (`true` -> `'full'`, `false` -> `'sidebar'`).
