### PR TITLE
Fix emoji picker

### LINKED ISSUE #831: Bug with emoji selector
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/caprine/issues/831)

When you go into a conversation if you click on the emoji button everything is fine. 

You click, you choose, you remove the chooser. Then if you use cmd+e works.

Now going into any conversation if you use cmd+e to open the selector, you choose your emoji, close it again with cmd+e and try to continue your message it will keep opening the emoji selector.

Workaround: Switch between conversation to unlock it and use the emoji button with mouse first then cmd+e won't trigger the bug

[Video](https://streamable.com/lh4cm)

---

Caprine 2.30.1
Electron 4.1.0
darwin 18.2.0
Locale: fr

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#941 Fix emoji selector popup](https://issuehunt.io/r/sindresorhus/caprine/pull/941)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/caprine/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by whitecrownclown**
Fixes #831 

@sindresorhus 	@CvX 

Issue is pretty much explained [here](https://github.com/sindresorhus/caprine/issues/831#issuecomment-498070981) by @CvX 

Explanation: Triggering `mouseover` fetches the popover module. When switching conversations, the emoji component unmounts and needs `mouseover` in order to function correctly with the keyboard shortcut.`Mutation Observer` is clunky and heavy on performance since we can't listen directly on the node we require. Polling is also unreliable.

I think this one is consistent & the most performant. Please have a look.Thanks!

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#831: Bug with emoji selector](https://issuehunt.io/repos/42574339/issues/831)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

File: source/browser.ts [hunk 1]
```diff
@@ -117,8 +117,10 @@ ipc.on('insert-gif', () => {
 	document.querySelector<HTMLElement>('._yht')!.click();
 });
 
-ipc.on('insert-emoji', () => {
-	document.querySelector<HTMLElement>('._5s2p')!.click();
+ipc.on('insert-emoji', async () => {
+	const emojiEl = await elementReady<HTMLElement>('._5s2p');
```
Comment (sindresorhus) [inline source/browser.ts]:
```suggestion
	const emojiElement = await elementReady<HTMLElement>('._5s2p');
```

File: source/browser.ts [hunk 2]
```diff
@@ -419,12 +421,23 @@ function closePreferences(): void {
 	doneButton.click();
 }
 
+async function insertionListener(event: AnimationEvent): Promise<void> {
+	if (event.animationName === 'nodeInserted') {
+		const emojiEl = await elementReady<HTMLElement>('._5s2p');
```
Comment (sindresorhus) [inline source/browser.ts]:
```suggestion
		const emojiElement = await elementReady<HTMLElement>('._5s2p');
```

File: source/browser.ts [hunk 3]
```diff
@@ -419,12 +421,23 @@ function closePreferences(): void {
...
+}
+
 // Inject a global style node to maintain custom appearance after conversation change or startup
-document.addEventListener('DOMContentLoaded', () => {
+document.addEventListener('DOMContentLoaded', async () => {
 	const style = document.createElement('style');
 	style.id = 'zoomFactor';
 	document.body.append(style);
 
+	const emojiContainer = await elementReady<HTMLElement>('._1t2u._7sli');
```
Comment (CvX) [inline source/browser.ts]: 1. It isn't a good idea to await for a specific element in this DOMContentLoaded callback. If the element is missing, e.g. because of Messenger UI update, it will not execute the rest of the callback. The `animationstart` setup has to be done in its own, separate, DOMContentLoaded callback.
2. You have the new Messenger UI, don't you? 😉In my instance, there's no '._1t2u._7sli', so the bugfix doesn't work and I get a non-dark-mode non-vibrant app because of the point above 😉

Comment (whitecrownclown) [reply source/browser.ts]: I see, yes, i have the new UI, i suppose i can use the document body in this case.

Comment (whitecrownclown) [reply source/browser.ts]: Screenshot 2019-06-21 at 15 27 53
Strange, i do see a parent for that commit

Comment (CvX) [reply source/browser.ts]:
```bash
~/dev/caprine fix/emoji-selector 9s
❯ git gc
error: Could not read 214f44c26bdff38c4e652b2aea0b40a153c9f5f9
error: Could not read 214f44c26bdff38c4e652b2aea0b40a153c9f5f9
error: Could not read 214f44c26bdff38c4e652b2aea0b40a153c9f5f9
error: Could not read 214f44c26bdff38c4e652b2aea0b40a153c9f5f9
fatal: Failed to traverse parents of commit 78ae346ed6838f15c96bbb78b53242b9fc4a3a19
fatal: failed to run repack
```

Well… gotta nuke my local repo! 😬 (a clean looks ok 😉)
